Function 
print_banner()
printf"${blue} ##########################################\n"
printf"${blue} ## NHba.    BAC94    MI           TVGS9    /BA9.       ##\n"
printf"${blue} ## N.  TA.    DAE...     NI                9        /P   \9.      ##\n"
printf"${blue} ## B.   DA.   EGI°°°    LP                G       NHAG      ##\n"
printf"${blue} ## ANP..      ZNGF5   NHG4A       Z      /F.   NY\     ##\n"
printf"${blue} ##########################################\n"
printf"${red}                                         DELTA                                      \n"
printf"${red}                                     by  -- ●- -● --- ●---                         \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} I. Adélie Linux   \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 2. Alpine Linux  \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 3. Arch Linux     \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 4. Artix Linux     \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 5. Chimera Linux \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 6. Debain             \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 7. deepin              \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 8. Fedora              \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 9. Manjaro           \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 10. OpenSUSE     \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 11. Pardus            \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 12. Rocky Linux  \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 13. Ubuntu (24.04) \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 14. Void Linux     \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 15. Kali linux full \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 16. Kali linux minimal \n"
printf"${RED}[${WHITE}03${RED}]${ORANGE} 17. Kali linux nano \n"
printf"${blue} Install selected one with: {red} Delta install <alias> \n"
